---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: VBox

platforms:
  - name: instance-${MOLECULE_ROLE_NAME:-molecule}-1
    groups:
      - jenkins
    box: centos/7
    memory: 1024
    cpus: 1

provisioner:
  name: ansible
  log: true
  options:
    become: true
  group_vars:
    jenkins:
      jenkins_java_jvm_memory: 1024

verifier:
  name: ansible
