---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: VBox

platforms:
  - name: instance-${MOLECULE_ROLE_NAME:-molecule}-1
    interfaces:
      - network_name: forwarded_port
        guest: 8080
        host: 8080
    groups:
      - jenkins
    box: centos/7
    memory: 1024
    cpus: 1

provisioner:
  name: ansible
  log: true
  options:
    become: true

verifier:
  name: ansible
