---

- name: Modify jenkins config file
  lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: "{{ item.regex }}"
    line:  "{{ item.line }}"
    backrefs: True
  with_items:
    - regex: '^JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true"$'
      line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Xmx{{ jenkins_config_java_jvm_memory | int | round }}m"'
    - regex: '^JENKINS_HOME='
      line: 'JENKINS_HOME="{{ jenkins_home }}"'
    - regex: '^JENKINS_PORT='
      line: 'JENKINS_PORT="{{ jenkins_config_port }}"'
  notify: Restart jenkins service
